nhcarrigan/becca-lyria

commands/ping.js

Added colors on embed depending on pingTime

---

package-lock.json
package.json
src/commands/leave.ts
src/commands/main.ts
src/commands/math.ts

Add a `math` command to the bot that takes an expression and evaluates it.
Closes #2

V 2.2.0 - add math command

---

package.json
src/commands.ts
src/commands/help.ts
src/main.ts

Refactor command handling - commands now get bootstrapped together in a separate file before importing to main file, allowing for easier imports to other files (like the help command). 
Fix help command - corrects the error of `null` command descriptions by changing from `readFile` to directly importing the commands (hence the change to command handling). 
Closes #32

Update help command, change command handling

---

package.json
src/commands/math.ts

Fixes a bug where the math command sent an error message even on success.
Closes #XXXXX

V 3.2.2 - fix math command

---

package.json
src/commands.ts
src/commands/guess.ts

Adds a little guess-the-number game.
Closes #XXXXX

V 3.3.0 - add guess command

---

package.json
src/commands/about.ts

The about command is currently not reading the files correctly. This PR updates the directory.
Closes #XXXXX

Update about command

---

package.json
src/commands/help.ts

Refactors the help command to list all available commands.
Closes #XXXXX

V 3.3.2 - Update help command

---

package.json
src/main.ts

The bot currently responds to commands in a DM channel. This disables that, and instead triggers a message containing a link to the home server.
Closes #XXXXX

V 3.3.3 - disable DMs

---

package.json
src/main.ts

Adds a webhook to notify when the bot comes online.
Closes #XXXXX

Add webhook

---

src/main.ts

Leverages the webhook functionality to add messages when the bot joins or leaves a server. Also adds a custom status.
Closes #XXXXX

Add webhook pings for join/leave servers, add custom status

---

package.json
src/main.ts

Modify the webhook messages to include the name.
Closes #XXXXX

Modify webhook messages

---

package.json
src/commands.ts
src/commands/jobs.ts

Adds a job search command.
Closes #XXXXX

V 3.6.0 - Add jobs command

---

package.json
src/commands.ts
src/commands/listen.ts
src/interfaces/listenerInt.ts
src/listeners.ts
src/listeners/heartsListen.ts
src/listeners/levelsListen.ts
src/listeners/usageListen.ts
src/main.ts

Add a command that details the listeners the bot implements.
Closes #XXXXX

V 3.7.0 - add listener command

---

package.json
src/commands/magic.ts

Magic command would still execute with no parameter provided - added return statement, removed author mention from error message.
Closes #XXXXX

V 4.1.1 - fix bug in magic command

---

package.json
src/COMMANDS.ts
src/commands/space.ts
src/interfaces/SpaceInt.ts

Adds a space command! 😁 
Closes #XXXXX

V 4.3.0 - add space command

---

package.json
src/commands/help.ts
src/main.ts

Change help command to message channel instead of a DM.
Closes #XXXXX

V 4.3.1 - remove DM from help command

---

package.json
src/commands/space.ts

Update space command to include link and copyright fallback
Closes #XXXXX

V 4.3.2 - Update Space command

---

package.json
src/COMMANDS.ts
src/commands/joke.ts
src/interfaces/JokeInt.ts

This PR adds a terrible joke command.
Closes #XXXXX

V 4.5.0 - Add joke command

---

package.json
src/COMMANDS.ts
src/commands/xkcd.ts
src/interfaces/XkcdInt.ts

This PR adds a command to fetch XKCD comics. 
Closes #XXXXX

V 4.6.0 - add XKCD command

---

package.json
src/main.ts

This PR edits the welcome DM embed to include the server's name.
Closes #XXXXX

Add server name to welcome embed

---

config.json
package.json
src/commands/ban.ts
src/commands/kick.ts
src/commands/restrict.ts
src/commands/warn.ts

This PR accomplishes two things. First, it adds protections to ensure the bot cannot be targeted by the `ban`, `kick`, `restrict`, and `warn` commands. Second, it modifies the channel creation process on the `restrict` command to ensure the appropriate permissions are granted for the moderators to access the channel.
Closes #XXXXX

Add protections, adjust restrict command

---

.travis.yml

This PR adds a check to confirm there are no build errors when running `tsc`
Closes #XXXXX

Add build step to travis

---

package.json
src/COMMANDS.ts
src/commands/fact.ts
src/interfaces/FactInt.ts

Adds a `fact` command that fetches a random fact.
Closes #XXXXX

Add fact command

---

src/interfaces/UsageInt.ts
src/interfaces/UserInt.ts
src/listeners/levelsListen.ts
src/listeners/usageListen.ts

This PR adds date information to the user and usage schemas. This will facilitate debugging issues with extraneous data being added to the DB.
Closes #XXXXX

Add date fields

---

.eslintrc.json
src/commands/github.ts
src/commands/hpspell.ts
src/commands/space.ts
src/listeners/levelsListen.ts
src/listeners/usageListen.ts

This PR adds an `eslint` rule to disallow single line code blocks. 
```js
if (x) return y
```
becomes:
```js
if (x) {
return y
}
```
Closes #XXXXX

No single line codeblocks

---

package.json
src/commands/levels.ts

This PR adds an optional usermention parameter to the `level` command, allowing a user to see someone else's ranking.
Closes #XXXXX

Add optional parameter to level

---

CONTRIBUTING.md
README.md

Makes some tweaks for Hacktoberfest.
Closes #XXXXX

Add hacktober to readme, add contributing.md

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/chore.md
.github/ISSUE_TEMPLATE/documentation.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/other.md
.github/labeler.yml
.github/workflows/dependabot.yml
.github/workflows/greetings.yml
.github/workflows/labeler.yml
.github/workflows/merge-conflict.yml
.github/workflows/stale.yml

This PR adds some extra workflow and restructures the labels for clarity - in preparation of possible contributors for Hacktoberfest!
Closes #XXXXX

Restructure

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/chore.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/documentation.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/other.md

Fix the broken issue templates.
Closes #XXXXX

Fix issue templates

---

package-lock.json
package.json

This PR fetches the latest linter versions to eliminate the erroneous `unused-var` warnings.
Closes #XXXXX

Update to linter

---

CONTRIBUTING.md
README.md

Cleans up the `README` and expands the `CONTRIBUTING`
Closes #125

Revise docs

---

PRIVACY.md
package.json
src/COMMANDS.ts
src/commands/privacy.ts
src/commands/user.ts
src/main.ts

Add a privacy policy and command, require consent for the user command. Should put us in line with Discord Developer terms.
Closes #XXXXX

Add privacy policy and command

---

package.json
src/main.ts

Adds a listener for the `messageUpdate` event to log edited messages.
Closes #XXXXX

Add message edit listener

---

package.json
src/main.ts

Delays the response to a command call by 3 seconds, adds the typing status.
Closes #XXXXX

Add response delay, typing feature

---

package.json
src/COMMANDS.ts
src/commands/config.ts

Adds a config command to show the current server settings. 
Closes #XXXXX

V 4.16.0 - add config command

---

package.json
src/COMMANDS.ts
src/commands/title.ts
src/interfaces/WordInt.ts

This adds a title command that leverages the [Noops wordbot](https://noopschallenge.com/challenges/wordbot).
Closes #XXXXX

[REQUEST] - Title Command

---

package.json
src/COMMANDS.ts
src/commands/challenge.ts
src/interfaces/ChallengeInt.ts

Adds a challenge command to get programming type challenges from the [Noops fizzbot](https://noopschallenge.com/challenges/fizzbot)
Closes #XXXXX

Add challenge command

---

package.json
src/COMMANDS.ts
src/commands/maze.ts
src/interfaces/MazeInt.ts

Adds a maze command thanks to the [Noops mazebot](https://noopschallenge.com/challenges/mazebot)
Closes #XXXXX

Add maze command

---

package.json
src/COMMANDS.ts
src/commands/adventure.ts
src/interfaces/AdventureInt.ts

Adds an adventure command using the [Noops pathbot](https://noopschallenge.com/challenges/pathbot).
Closes #XXXXX

Add adventure command

---

package.json
src/commands/challenge.ts
src/commands/maze.ts

Corrects some copy-pasta errors in the new commands.
Closes #XXXXX

Fix a few copy-paste errors

---

src/COMMANDS.ts
src/commands/report.ts

Added a report command which when executed gives a link to the issues page where user can file an issue.

Add report command

---

src/main.ts

Removes the welcome DM received by the bot when a user joins the server the bot is in.

Removed Welcome DM

---

src/commands/games/challenge.ts

Fixes a bug in the argument handling of the `challenge` command.
Closes #XXXXX

Fix challenge command bug

---

src/commands/games/challenge.ts
src/commands/games/riddle.ts

Fixed exception on riddle command, and added stylized error messages to users on challange and riddle command.
Also changed forming answer from one args to full sentence in answer to a riddle.
Closes #194

Fix Challange and Riddle handling bad responses

---

package-lock.json
package.json

This PR updates the `npm` packages to the latest version, updates the node engine to the latest version, and updates the bot version.
Closes #XXXXX

[CHORE] Update dependencies, versioning

---

README.md

Remove the contribs table, switching to a bot to handle it.
Closes #XXXXX

Remove manual contribs table

---

src/commands/games/sus.ts

This PR adds colours to the `sus` embed to match the colours from the game.
Closes #XXXXX

feat: Add colours to embed

---

README.md
package.json
src/commands/bot/about.ts
src/commands/games/joke.ts
test/unit/commands/bot/about.spec.ts

Re-brands the bot -- now named after my old RP character. Because why not.
Closes #XXXXX

Name change

---

src/commands/server/config.ts

This PR fixes a bug in the way the bot handles my additions to the `config` embed.
Closes #XXXXX

Fix prefix bug

---

src/botConnect.ts
src/database/main.ts

A quick tweak to the database connection message.
Closes #XXXXX

Change DB message

---

.all-contributorsrc
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
README.md
package.json
src/commands/bot/about.ts
src/commands/bot/privacy.ts
src/commands/bot/report.ts
src/commands/games/joke.ts
src/commands/general/star.ts
test/unit/commands/bot/about.spec.ts

Updates the links throughout the codebase to reflect the new repository name.
Closes #XXXXX
For _any_ version updates, please verify if the [documentation page](https://www.nhcarrigan.com/discord-bot-documentation) needs an update. If it does, please [create an issue there](https://github.com/nhcarrigan/discord-bot-documentation) to ensure it is not forgotten.

Replace links

---

README.md

Intellectual property theft is bad, kids. This PR adds much deserved credit for the server/bot art.
Closes #XXXXX

Add art credit

---

package-lock.json
package.json
src/serve.ts

Adds a tiny express HTTP route for the DO App Container health check.
Closes #XXXXX

Add route for DO health check

---

package.json
src/commands/general/star.ts

This fixes the star command (which broke when I renamed the repo). Rather than using a direct image URL, I went with the `MessagAttachment` route to avoid future breaks.
Closes #XXXXX

Fix star image

---

package.json
src/commands/bot/contributors.ts
src/interfaces/commands/ContributorInt.ts

Adds a `contributors` command to recognise all of you for your hard work! 🙂 
Closes #XXXXX

Add new command!

---

package.json
src/commands/server/config.ts
src/interfaces/commands/ArtInt.ts

Modifies the `config` command to check for `Manage Server` permissions instead of `Administrator`. 
Also hard-codes my ID as a bypass to allow for development adjustment.
Closes #XXXXX

Adjust permissions needed for config

---

package.json
src/commands/moderation/restrict.ts
src/commands/moderation/unrestrict.ts

Changes the `restrict` command to remove previous roles.
Closes #XXXXX

Change command to remove all other roles first

---

package.json
src/commands/games/inulove.ts
src/commands/games/inuquote.ts
src/interfaces/commands/InuQuoteInt.ts
src/utils/commands/inuLoveList.ts
src/utils/commands/inuQuoteList.ts

Add inuyasha commands

---

README.md

rm -rf fossa

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

Adds reminder to contributors to add tests over their changes.

docs(test): reminder to contributors to add tests

---

.github/workflows/node-ci.yml
coverage.json
package-lock.json
package.json

Adds the `codecov` integration - this *should* generate coverage reports on each PR.
Closes #XXXXX

Here we go

---

CODE_OF_CONDUCT.md
README.md

Add a Code of Conduct file to the documentation, and tweak the readme a bit.
Closes #XXXXX

docs: Add Code of Conduct

---

package.json
src/events/onMessage.ts

Adds a feature that allows the bot to react to mentions when a command isn't called.
Closes #XXXXX

Add response to mentions

---

package.json
src/commands/server/config.ts
src/commands/server/leave.ts
src/events/onMessage.ts

Refactors my Discord ID into an environment variable (in case someone runs their own instance), adjusts how the bot responds to that environment variable.
Closes #XXXXX

Respond to bot owner

---

PRIVACY.md

Updates the Privacy Policy to document the data deleted when the bot leaves a server.
Closes #135 

Update privacy policy

---

package.json
src/commands/bot/support.ts
src/events/onMessage.ts
test/unit/commands/bot/support.spec.ts

Adds a support command that returns a link to the support server.
Closes #XXXXX

Add support command

---

package.json
src/listeners/botMentionListener.ts

Fixes the `[Object object]` bug on the bot mention event.
Closes #XXXXX

Fix bug with prefix

---

package.json
src/commands/bot/invite.ts
test/unit/commands/bot/invite.spec.ts

Updates the permissions scope on the invite link to include "Embed Links" and "Add Reactions" - discovered a permissions error on a server where these were disabled for the `everyone` role.
Closes #XXXXX
For _any_ version updates, please verify if the [documentation page](https://www.nhcarrigan.com/BeccaBot-documentation) needs an update. If it does, please [create an issue there](https://github.com/nhcarrigan/BeccaBot-documentation/issues/new?assignees=nhcarrigan&labels=%F0%9F%9A%A6+status%3A+awaiting+triage&template=update.md&title=%5BUPDATE%5D) to ensure …

Correct permissions link

---

package-lock.json
package.json
src/botConnect.ts
src/commands/server/list.ts

- Fixed the `undefined` owner name on the `list` command.
- Now, you can use a pagination with the `list` command. e.g.: `list 2`.
- Changed bot version to `6.6.2`.

fix(command): list command by page and undefined owner name

---

.env.example
package-lock.json
package.json
src/commands/bot/block.ts
src/database/models/BlockedUserModel.ts
src/events/onMessage.ts
src/interfaces/ListenerInt.ts
src/listeners/blockedUserListener.ts
src/listeners/interceptableLevelsListener.ts
src/listeners/interceptableUsageListener.ts

Adds a feature to allow the bot owner to block users, based on reports of spam/abuse.
Closes #146 

Add block command

---

package-lock.json
package.json
src/commands/games/piglatin.ts
test/unit/commands/games/piglatin.spec.ts

Adds a pig latin translation command.
Closes #XXXXX

Add pig latin command

---

package.json
src/commands/server/server.ts

Restores the server member count feature as the intent is approved for the welcome messages.
Closes #XXXXX

Restore server member counts

---

LICENSE.md
README.md
package.json

Replaces the license in the docs.
Closes #XXXXX

docs: New License

---

package.json
src/commands/general/becca.ts

Adds a command to return character information about Becca.
Closes #XXXXX

feat: Add Becca command

---

package.json
src/commands/general/becca.ts

Expands the `becca` command to include the information from the website bio.
Closes #XXXXX

fix: Add full details to bio.

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

Replaces the `CONTRIBUTING.md` file with our
standard template. Removes the code coverage
checklist from the pull request template.
Closes #XXXXX

docs: Update contributing and PR template

---

package.json
src/utils/commands/artList.ts

Adds the Samsung images used to make the server emoji to the `art` command.
Closes #XXXXX

feat: Add samsung art

---

package-lock.json
package.json
src/commands/bot/contributors.ts

This pull request does the following:
This command should be refactored to do the following:
- Set the `title` to "Thanks to these wonderful contributors:"
- Set the `description` to a comma separated list of contributor names.
- Set the `footer` to a link to the repository README.
- Set embed `colour` to the default message colour for becca.
Closes #458 

Updated Contributors embed

---

package-lock.json
package.json
src/events/onMessageDelete.ts
src/events/onMessageUpdate.ts
src/utils/substringHelper.ts

Fixes the bug where the logging embeds would error out on long messages. Uses a modular helper function to substring the message based on length.
Closes #XXXXX

fix: logging embeds

---

package-lock.json
package.json
src/commands/games/riddle.ts

Adds a field to the `riddle` command's `request` embed that includes the command to submit a solution.
Closes #463

fix: riddle command

---

package-lock.json
package.json
src/commands/bot/help.ts
src/commands/emote/boop.ts
src/commands/emote/hug.ts
src/commands/emote/tickle.ts
src/interfaces/CommandInt.ts

feat: Emote Commands

---

package-lock.json
package.json
src/utils/commands/artList.ts

Adds the art that whisperdawn provided
Closes #XXXXX

feat: More art

---

package-lock.json
package.json
src/utils/commands/artList.ts

feat: even more art

---

.github/workflows/node-ci.yml
package.json

Slight modification of the workflow in preparation for restoring the tests.
Closes #XXXXX

tools: tweak workflow

---

.env.example
package-lock.json
package.json
src/database/models/CommandLogModel.ts
src/database/models/LevelModel.ts
src/database/models/ServerModel.ts

Adds configuration to keep data encrypted at rest. Existing data cannot be migrated in a sweep, but will be updated as documents are accessed through the bot.
Closes #XXXXX

feat: encryption

---

package-lock.json
package.json
src/utils/commands/artList.ts

Woohoo! New commission!
Closes #XXXXX

feat: add starfazers art

---

package-lock.json
package.json
src/events/onMessageUpdate.ts

[BUG] - messageUpdate triggering on false positives #528
Closes #XXXXX

messageUpdate triggering on false positives

---

package-lock.json
package.json
src/commands/server/level.ts

Resolves a bug with the database encryption converting the date object to a string object.
Closes #XXXXX

fix: level date bug

---

package-lock.json
package.json
src/commands/server/resetlevel.ts

feat: add reset level command

---

package-lock.json
package.json
src/commands/server/leaderboard.ts
src/commands/server/resetlevel.ts

Adds a command which returns the server's top ten members by level and the caller's current rank.
Closes #XXXXX

feat: add leaderboard command

---

package.json

Revert the accidental removal of the module aliases.
Closes #XXXXX

fix: revert modules

---

.github/workflows/codeql-analysis.yml

tools: new codeql

---

package-lock.json
package.json
src/commands/games/habitica.ts

Resolves the error handling when a user string is not found.
Closes #XXXXX

fix: habitica command

---

package-lock.json
package.json
src/commands/server/suggest.ts

Send the suggest embed to the suggestion channel, not the channel
the command was called in.
Closes #XXXXX

fix: suggest embed sending

---

src/commands/server/suggest.ts

Because the database stores ID strings, not channel names...
Closes #XXXXX

fix: suggest command AGAIN

---

package-lock.json
package.json
src/botConnect.ts
src/utils/server/httpEndpoint.ts

Adds a small HTTP endpoint to allow for uptime monitoring.
Closes #XXXXX

feat: http endpoint

---

package-lock.json
package.json
src/botConnect.ts
src/utils/server/httpEndpoint.ts

It helps to actually load the credentials into the HTTPS protocol.
Closes #XXXXX

fix: server

---

package-lock.json
package.json
src/utils/server/httpEndpoint.ts

Forgot to replace `example.com` oops.
Closes #XXXXX

fix: forgot domain

---

package-lock.json
package.json
src/utils/extendsClientToBeccaInt.ts

Add the standard try/catch handler to the `sendMessageToLogsChannel` method.
Closes #550 

feat: log message error handling

---

package-lock.json
package.json
src/events/onMessage.ts

Change the logic order to avoid awarding experience when commands
are called.
Closes #XXXXX

fix: no levels on command

---

package-lock.json
package.json
src/botConnect.ts
src/commands/general/maths.ts
src/serve.ts
src/utils/beccaErrorHandler.ts

Need to JSON stringify any error objects to parse them correctly.
Closes #XXXXX

fix: error handler

---

README.md

Add standard badges to readme.
Closes #XXXXX

docs: standard badges

---

package-lock.json
package.json
src/listeners/levelsListener.ts
src/utils/commands/levelScale.ts

1000 isn't feasible to reach. Ever. 100 is.
Closes #XXXXX

feat: reduce level scale

---

package-lock.json
package.json
src/listeners/levelsListener.ts

Add a reaction to the message when the user gains experience
points.
Add a reaction to messages which fire the level listener.
Closes #XXXXX

feat: react on levels

---

package-lock.json
package.json
src/commands/server/levelscale.ts

Add a command which returns the full level scale.
Closes #XXXXX

feat: add levelscale command

---

package-lock.json
package.json
src/commands/general/becca.ts
src/commands/moderation/closeChannel.ts
src/commands/server/suggest.ts

- Changes the `becca` command to return a link to her portfolio instead.
- Removes the confirmation reaction from the `close` command.
Closes #XXXXX

feat: general updates

---

package-lock.json
package.json
src/commands/server/leaderboard.ts
src/commands/server/level.ts
src/commands/server/levelscale.ts
src/listeners/levelsListener.ts

Modify the levelling system to use a nickname for the data object
if available.
Closes #XXXXX

feat: use nicknames

---

package-lock.json
package.json
src/commands/server/role.ts

Rather than a specific parameter, get the role list when you omit
the role to assign.
Closes #XXXXX

fix: get role list

---

package-lock.json
package.json
src/commands/moderation/ban.ts

In this, the code for the DM Logic and the Ban action is switched and put in the right order for correct execution.
Closes #606

Corrected the order of DM Logic and Ban Action in ban.ts

---

package-lock.json
package.json
src/commands/general/starcount.ts
src/commands/server/resetstar.ts

Add a command to reset the star counts in a server, tied to the
manage guild permissions.
Closes #XXXXX

feat: add resetstar command

---

package-lock.json
package.json
sample.env
src/commands/server/resetstar.ts

Forgot to add the error handler to the new `resetstar` command.
Closes #XXXXX

fix: error handler for resetstar

---

src/commands/general/colour.ts

- Adds a `colour` command which takes a hex code and renders that colour.
Closes #XXXXX

feat: colour command

---

package-lock.json
package.json
src/commands/server/config.ts
src/utils/config/defaultValues.ts
src/utils/config/keyList.ts
src/utils/config/viewBlockedEmbed.ts
src/utils/config/viewConfigEmbed.ts
src/utils/config/viewHeartsEmbed.ts
src/utils/config/viewRolesEmbed.ts
src/utils/extendsClientToBeccaInt.ts

Refactors the config command to allow for deleted roles + users to
be removed. Also cleans up the methods for viewing configs.
Closes #XXXXX

feat: refactor config

---

package-lock.json
package.json
src/utils/config/viewHeartsEmbed.ts

Forgot the new-line separator in this embed.
Closes #XXXXX

fix: config embed

---

package-lock.json
package.json
src/commands/server/suggestion.ts

Add a `suggestion` command, which server managers can use to approve or deny suggestions.
Closes #XXXXX

feat: add suggestion command

---

package-lock.json
package.json
src/botConnect.ts
src/utils/beccaErrorHandler.ts

feat: error handling

---

src/commands/server/config.ts
src/commands/server/role.ts
src/commands/server/server.ts

- Modify the verbiage of the role command
- Remove the role list from the server embed.
Closes #XXXXX

fix: verbiage

---

package-lock.json
package.json
src/commands/games/sus.ts

feat: amogus

---

package-lock.json
package.json
src/commands/general/orbit.ts
src/interfaces/commands/OrbitInt.ts

Add an individual member orbit score to the orbit command.
Closes #XXXXX

feat: individual orbit score

---

package-lock.json
package.json
src/commands/moderation/ban.ts
src/commands/moderation/kick.ts
src/commands/moderation/restrict.ts
src/commands/moderation/warn.ts
src/commands/moderation/warnCount.ts
src/database/models/WarningModel.ts
src/events/onGuildMemberAdd.ts
src/events/onGuildMemberRemove.ts
src/events/onMessageDelete.ts
src/events/onMessageUpdate.ts

- Add confirmation when `warn` action is complete.
- Add database entry to track number of warnings a user receives in a server.
- Update embeds to use `author` field.
Closes #660 

feat: moderation updates

---

package-lock.json
package.json
src/commands/moderation/ban.ts
src/commands/moderation/kick.ts
src/commands/moderation/restrict.ts
src/commands/moderation/unrestrict.ts
src/commands/moderation/warn.ts
src/commands/moderation/warnCount.ts
src/events/onGuildMemberAdd.ts
src/events/onGuildMemberRemove.ts
src/events/onMessageDelete.ts
src/events/onMessageUpdate.ts

feat: log user and message IDs

---

package-lock.json
package.json
src/events/messageEvents/messageDelete.ts

Uses the author `username` property instead of the `id` property for the author value in the delete embed.
Closes #XXXXX

fix: delete embed

---

package-lock.json
package.json
src/commands/server/list.ts
src/events/guildEvents/guildCreate.ts

Update the logic to fetch guild owners properly.
Closes #XXXXX

fix: better owner info handling

---

README.md

- Update copyright year to 2021 in `README.md`.

[fix/docs] Update copyright year to 2021

---

.github/PULL_REQUEST_TEMPLATE.md

- Improved the pull request template.
- Removed the `:` in headers.
- Added link to the contributing guidelines in the first Markdown comment.
- Colorized with black the `NOT` and `DOES` words at the bottom.

[docs] Improved pull request template

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/chore.yml
.github/ISSUE_TEMPLATE/documentation.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/ISSUE_TEMPLATE/other.yml

Tweaks the issue forms that @Panquesito7 kindly provided, making the following changes:
- Because our prompts are all long-form answers, changed the inputs from `input` to `textarea` to allow multi-line responses.
- Shortened the `label` properties and leveraged the `description` properties to clarify each field. 
- Reworded the feature request template for better UX.
Closes #XXXXX
For _any_ version updates, please verify if the [documentation page](https://www.beccalyria.com/discord-documentation) needs an update. If it does, please [create an issue there](https://github.com/BeccaLyria/discord-documentation/issues/new?assignees=nhcarrigan&labels=%F0%9F%9A%A6+status%3A+awaiting+triage&template=update.md&title=%5BUPDATE%5D) to …

chore: tweak issue templates

---

package-lock.json
package.json
src/events/guildEvents/guildDelete.ts

- Fix guild delete event text.
Closes #695 

fix: guild delete event text

---

package-lock.json
package.json
src/commands/server/config.ts
src/config/database/defaultServer.ts
src/database/models/ServerModel.ts
src/interfaces/settings/SettingsTypes.ts
src/listeners/levelListener.ts
src/modules/commands/config/validateSetting.ts
src/modules/commands/config/viewSettings.ts
src/modules/settings/setSetting.ts

Adds a new `level_channel` config, which allows a server to set a specific channel for level up messages. If this is set (and is still a valid channel), Becca will send the level up messages there instead of in the channel where the message was sent.
Closes #XXXXX

feat: level logs

---

package-lock.json
package.json
src/server/serve.ts

Update the ports for non-root access and NGINX.
Closes #XXXXX

fix: update ports

---

package-lock.json
package.json
src/commands/general/userinfo.ts
src/commands/server/server.ts
src/config/commands/serverInfo.ts
src/index.ts

Expands the `userinfo` and `server` commands to include more information.
Closes #XXXXX

feat: expand info commands

---

package-lock.json
package.json
src/commands/server/config.ts
src/config/database/defaultServer.ts
src/database/models/ServerModel.ts
src/events/messageEvents/messageSend.ts
src/interfaces/settings/SettingsTypes.ts
src/listeners/linksListener.ts
src/modules/commands/config/validateSetting.ts
src/modules/commands/config/viewSettings.ts
src/modules/commands/config/viewSettingsArray.ts
src/modules/settings/setSetting.ts

feat: anti link system

---

package-lock.json
package.json
src/commands/server/config.ts
src/config/database/defaultServer.ts
src/database/models/ServerModel.ts
src/interfaces/settings/SettingsTypes.ts
src/listeners/linksListener.ts
src/modules/commands/config/validateSetting.ts
src/modules/commands/config/viewSettings.ts
src/modules/commands/config/viewSettingsArray.ts
src/modules/settings/setSetting.ts

Add a config that allows servers to set permitted link formats (in the form of a regex) that won't trigger the anti-link detection.
Closes #XXXXX

feat: allowed links

---

.gitignore
package-lock.json
package.json
src/commands/server/config.ts
src/config/database/defaultServer.ts
src/database/models/ServerModel.ts
src/interfaces/settings/LevelRoleInt.ts
src/interfaces/settings/SettingsTypes.ts
src/listeners/levelListener.ts
src/modules/commands/config/renderSetting.ts
src/modules/commands/config/validateSetting.ts
src/modules/commands/config/viewSettings.ts
src/modules/commands/config/viewSettingsArray.ts
src/modules/settings/setSetting.ts

- Enables a `level_roles` setting to declare specific levels at which users should earn a role.
- Refactors the level listener logic to better handle new guilds and new members.
- Adds logic to assign the roles on level up, and log a message that the user earned the role.
Closes #XXXXX

feat: level roles

---

package-lock.json
package.json
src/commands/games/sus.ts
src/config/commands/susList.ts

Fixes Issue #710
Updated the sus command and renamed  `SusList.ts` to `susList.ts`.

Updated the Sus command.

---

package-lock.json
package.json
src/config/commands/artList.ts

Adds additional art to the bot's collection.
Closes #XXXXX

feat: new art

---

package-lock.json
package.json
src/events/voiceEvents/voiceStateUpdate.ts

A hot fix to address an issue where muting/unmuting triggered the log.
Closes #XXXXX

fix: voice events

---

package-lock.json
package.json
src/listeners/linksListener.ts

Properly handles messages with multiple links where only some match the allowed links regexes.
Closes #XXXXX

fix: links

---

package-lock.json
package.json
sample.env
src/database/models/LevelModel.ts
src/database/models/ServerModel.ts
src/database/models/StarModel.ts
src/database/models/WarningModel.ts
src/modules/commands/config/viewSettings.ts
src/modules/validateEnv.ts

Removes the DB encryption, as it prevented migration of data.d
Closes #XXXXX

feat: db migration

---

package-lock.json
package.json
sample.env
src/index.ts
src/interfaces/BeccaInt.ts
src/modules/commands/server/validateChannelPerms.ts
src/modules/commands/server/validateServerPerms.ts
src/modules/validateEnv.ts

Discord.js 13 released - switch from `dev` to `latest` again.
Updates other deps, resolves build errors.
Closes #XXXXX

feat: dep updates

---

package.json
src/listeners/linksListener.ts

Blocks more domains with `.*{3}`, for example `.dev`
closes #732 
GitHub Action could automate this

fix: block more domains (#732)

---

package-lock.json
package.json

fix: versioning

---

package-lock.json
package.json
src/listeners/levelListener.ts

Adjusts the level messaging system to use embeds for better clarity in message.
Closes #724 

feat: level message ping

---

package-lock.json
package.json
src/config/database/defaultServer.ts
src/database/models/ServerModel.ts
src/events/memberEvents/memberRemove.ts
src/interfaces/settings/SettingsTypes.ts
src/modules/commands/config/renderSetting.ts
src/modules/commands/config/validateSetting.ts
src/modules/commands/config/viewSettings.ts
src/modules/settings/setSetting.ts

Adds a new config, `leave_message`, which allows a server to customise text that appears in the `memberRemove` embed.
Closes #XXXXX

feat: custom leave

---

package-lock.json
package.json
src/commands/general/topic.ts
src/config/commands/topicList.ts

Adds a `topic` command, which returns a random conversation starter.
Closes #XXXXX

feat: topics

---

package-lock.json
package.json
sample.env
src/events/guildEvents/guildDelete.ts
src/events/handleEvents.ts
src/events/interactionEvents/interactionCreate.ts
src/index.ts
src/interfaces/BeccaInt.ts
src/interfaces/slash/SlashInt.ts
src/modules/validateEnv.ts
src/slash/general/ping.ts
src/slash/loadSlash.ts
src/slash/registerSlash.ts
src/utils/readSlashDirectory.ts

Creates the first slash command!
Closes #XXXXX

feat: first slash command!

---

package-lock.json
package.json
src/commands/bot/help.ts
src/commands/games/cat.ts
src/commands/games/fact.ts
src/commands/games/guess.ts
src/commands/games/joke.ts
src/commands/games/mtg.ts
src/commands/games/sus.ts
src/commands/games/trivia.ts
src/interfaces/settings/ArraySettingsType.ts
src/modules/commands/config/viewSettingsArray.ts
src/modules/slash/community/handleRole.ts
src/modules/slash/config/handleReset.ts
src/modules/slash/config/handleSet.ts
src/modules/slash/config/handleView.ts
src/modules/slash/games/handleFact.ts
src/modules/slash/games/handleJoke.ts
src/modules/slash/games/handleMtg.ts
src/modules/slash/games/handleSus.ts
src/modules/slash/games/handleTrivia.ts
src/slash/games/games.ts
src/slash/loadSlash.ts
src/slash/server/config.ts

Migrates the game commands to slash.
Closes #XXXXX

feat: migrate all day long

---

package-lock.json
package.json
src/commands/bot/help.ts
src/commands/moderation/ban.ts
src/commands/moderation/kick.ts
src/commands/moderation/mute.ts
src/commands/moderation/unmute.ts
src/commands/moderation/warn.ts
src/commands/moderation/warncount.ts
src/interfaces/BeccaInt.ts
src/modules/commands/moderation/updateWarningCount.ts
src/modules/slash/moderation/handleBan.ts
src/modules/slash/moderation/handleKick.ts
src/modules/slash/moderation/handleMute.ts
src/modules/slash/moderation/handleUnmute.ts
src/modules/slash/moderation/handleWarn.ts
src/modules/slash/moderation/handleWarnCount.ts
src/modules/validateEnv.ts
src/slash/loadSlash.ts
src/slash/moderation/mod.ts

Closes #XXXXX
IDK why I'm versioning these I'm doing a major bump when we're done.

feat: mod-grate the mod commands

---

package-lock.json
package.json
src/commands/bot/help.ts
src/commands/server/permissioncheck.ts
src/commands/server/resetlevel.ts
src/commands/server/resetstar.ts
src/commands/server/server.ts
src/commands/server/suggest.ts
src/commands/server/suggestion.ts
src/modules/slash/community/handleServer.ts
src/modules/slash/community/handleSuggest.ts
src/modules/slash/manage/handleResetLevels.ts
src/modules/slash/manage/handleResetStars.ts
src/modules/slash/manage/handleSuggestion.ts
src/modules/slash/misc/handlePermissions.ts
src/slash/general/community.ts
src/slash/misc/misc.ts
src/slash/server/manage.ts

Everything is slashy now!
Closes #XXXXX

feat: last migration

---

package-lock.json
package.json
src/listeners/levelListener.ts

Save the level document *before* sending the message, in case the message send errors out.
Closes #XXXXX

fix: level logic

---

package-lock.json
package.json
sample.env
src/commands/currency.ts
src/database/models/CurrencyModel.ts
src/index.ts
src/interfaces/BeccaInt.ts
src/interfaces/commands/CurrencyHandler.ts
src/modules/commands/subcommands/currency/handleClaim.ts
src/modules/commands/subcommands/currency/handleDaily.ts
src/modules/commands/subcommands/currency/handleView.ts
src/modules/commands/subcommands/currency/handleWeekly.ts
src/modules/validateEnv.ts
src/utils/parseSeconds.ts

Adds a currency system with rewards tied to the support server.
Closes #XXXXX

feat: currency system

---

package-lock.json
package.json
src/commands/currency.ts
src/modules/commands/subcommands/currency/handleAbout.ts
src/modules/commands/subcommands/currency/handleClaim.ts

Tweak the verbiage a bit and add an about command.
Closes #XXXXX

feat: currency tweaks

---

package-lock.json
package.json
src/database/models/UsageModel.ts
src/events/interactionEvents/interactionCreate.ts
src/listeners/usageListener.ts

Track slash command usages (just the number of uses, no discord data).
Closes #XXXXX

feat: usage tracking

---

package-lock.json
package.json
src/database/connectDatabase.ts
src/interfaces/commands/CommandInt.ts
src/utils/beccaErrorHandler.ts

Handle the two broken package updates.
Closes #XXXXX

feat: package updates

---

package-lock.json
package.json
src/listeners/linksListener.ts

Fixes issues with false positives in the regex.
Closes #771 

fix: repair regex

---

package.json
src/listeners/linksListener.ts

fix: catch more urls, allow files (#777)

---

package.json
src/listeners/linksListener.ts

fix: YouTube short links

---

package-lock.json
package.json
src/listeners/linksListener.ts

Modify the regex to only look at links at the beginning of a word.
Closes #783 

fix: links again

---

package-lock.json
package.json
src/events/messageEvents/messageCreate.ts
src/index.ts

With the new process to update slash commands (or delete them), no longer need to reload all of them on start.
Closes #XXXXX

feat: no auto reload

---

package-lock.json
package.json
src/commands/currency.ts
src/events/interactionEvents/interactionCreate.ts
src/listeners/currencyListener.ts
src/modules/commands/subcommands/currency/handleClaim.ts

Award currency on command use. Modify the rewards to remove the nitro and increase the cost of all other rewards.
Closes #XXXXX

feat: currency

---

src/listeners/linksListener.ts

`in` links getting through, also picked some popular country codes https://en.wikipedia.org/wiki/Country_code_top-level_domain
Closes #790 

fix: more country codes for TLDs

---

package-lock.json
package.json
src/contexts/bookmark.ts
src/events/interactionEvents/interactionCreate.ts
src/index.ts
src/interfaces/BeccaInt.ts
src/interfaces/contexts/ContextInt.ts
src/utils/loadContexts.ts
src/utils/registerCommands.ts

Adds Becca's first context menu command, which allows you to bookmark a message for safe keeping!
Closes #XXXXX

feat: bookmark

---

package-lock.json
package.json
src/contexts/activity.ts
src/contexts/bookmark.ts
src/database/models/ActivityModel.ts
src/events/interactionEvents/interactionCreate.ts
src/modules/commands/logActivity.ts

- Add listener to count interactions with Becca
- Add user context command to see a user's interactions
- Add delete button to bookmarks
Closes #XXXXX

feat: activity

---

.huskyrc
package-lock.json
package.json
src/commands/currency.ts
src/commands/nhcarrigan.ts
src/config/optout/ActivityOptOut.ts
src/config/optout/CurrencyOptOut.ts
src/config/optout/LevelOptOut.ts
src/config/optout/StarOptOut.ts
src/listeners/currencyListener.ts
src/listeners/levelListener.ts
src/modules/commands/logActivity.ts
src/modules/commands/subcommands/community/handleStar.ts
src/modules/commands/subcommands/currency/handleGuess.ts
src/modules/commands/subcommands/nhcarrigan/handlePurge.ts
src/utils/beccaErrorHandler.ts

Got a little carried away with this one...
- Adds a config for opting out of the data-collection features.
- Validates that a user is not opted-out.
- Adds an owner command to purge a user's data.
- Adds the `guess` game.
Closes #XXXXX

feat: guess

---

package-lock.json
package.json
src/commands/config.ts
src/config/database/defaultServer.ts
src/contexts/bookmark.ts
src/contexts/report.ts
src/database/models/ServerModel.ts
src/events/interactionEvents/interactionCreate.ts
src/interfaces/contexts/ContextInt.ts
src/interfaces/settings/SettingsTypes.ts
src/modules/commands/config/renderSetting.ts
src/modules/commands/config/validateSetting.ts
src/modules/commands/config/viewSettings.ts
src/modules/settings/setSetting.ts

Adds a context menu option and related config settings to allow members to report a message to the moderation team.
Closes #XXXXX

feat: report

---

package-lock.json
package.json
src/commands/config.ts
src/config/database/defaultServer.ts
src/database/models/ServerModel.ts
src/interfaces/settings/ArraySettingsType.ts
src/interfaces/settings/SettingsTypes.ts
src/listeners/levelListener.ts
src/modules/commands/config/renderSetting.ts
src/modules/commands/config/validateSetting.ts
src/modules/commands/config/viewSettings.ts
src/modules/settings/setSetting.ts

Adds a config to allow for specific channels to be set as invalid for the experience system.
Closes #746 

feat: level ignore

---

package-lock.json
package.json
src/interfaces/commands/CommandDataInt.ts
src/modules/commands/subcommands/nhcarrigan/handleRegister.ts
src/modules/commands/subcommands/nhcarrigan/handleUnregister.ts
src/modules/commands/subcommands/nhcarrigan/handleViewSlash.ts

Addition of context commands introduced some bugs in the command-management tools.
Closes #XXXXX

fix: general tweaks

---

package-lock.json
package.json
src/config/commands/slotsList.ts
src/modules/commands/subcommands/currency/handleSlots.ts
src/server/serve.ts

- Update the cooldown message for the `slots` command
- Add the three new Becca emotes to the slots array
- Add endpoints to the http server to connect to a dashboard pog
Closes #XXXXX

feat: endpoints

---

package-lock.json
package.json
src/server/serve.ts

feat: cors

---

package-lock.json
package.json
src/database/models/LevelModel.ts
src/database/models/StarModel.ts
src/listeners/levelListener.ts
src/modules/commands/subcommands/community/handleLeaderboard.ts
src/modules/commands/subcommands/community/handleLevel.ts
src/modules/commands/subcommands/community/handleStar.ts
src/modules/commands/subcommands/community/handleStarCount.ts

Modify the structure of the level and star data to save properties needed for the dashboard.
Closes #XXXXX
Need to update the privacy policy to reflect the new data.

fix: store correct data

---

package-lock.json
package.json
src/interfaces/becca/CountInt.ts
src/modules/becca/getCounts.ts
src/modules/commands/subcommands/becca/handleAbout.ts
src/modules/commands/subcommands/community/handleLeaderboard.ts
src/modules/commands/subcommands/community/handleStarCount.ts
src/server/serve.ts

- Adds a dynamically generated URL for the dashboard to the `leaderboard` and `starcount` commands.
- Adds a helper to aggregate Becca's guild count, member count, and command count.
- Adds an endpoint to expose that aggregated data.
Closes #XXXXX

feat: counts and urls

---

package-lock.json
package.json
src/modules/commands/subcommands/community/handlePoll.ts

Wish typescript would catch `=` instead of `===` smh
Closes #XXXXX

fix: poll command

---

.github/PULL_REQUEST_TEMPLATE.md
package-lock.json
package.json
src/commands/becca.ts
src/config/commands/updatesData.ts
src/events/guildEvents/guildDelete.ts
src/modules/commands/subcommands/becca/handleUpdates.ts

- Adds a new `update` command to show Becca's latest changes and next scheduled release.
Closes #XXXXX

feat: releases

---

package-lock.json
package.json
src/config/commands/updatesData.ts

Updates changelog for this week's release
Closes #XXXXX

release: 16.20.0

---

src/config/listeners/linkRegex.ts

Closes #838 
For _any_ version updates, please verify if the [documentation page](https://www.beccalyria.com/discord-documentation) needs an update. If it does, please [create an issue there](https://github.com/BeccaLyria/discord-documentation/issues/new?assignees=nhcarrigan&labels=%F0%9F%9A%A6+status%3A+awaiting+triage&template=update.md&title=%5BUPDATE%5D) to ensure it is not forgotten

fix: stop ee links (#838)

---

src/config/commands/emoteList.ts

- Adds a placeholder `emoteList` value to prepare for command creation.
Closes #XXXXX

chore: add emote list placeholder

---

package-lock.json
package.json
src/config/commands/updatesData.ts

release: 16.20.2

---

src/modules/commands/subcommands/community/handleStar.ts
src/modules/commands/subcommands/games/handleMtg.ts

The links pertaining to the change of CDN server have been updated. The following files have been edited 
`src/modules/commands/subcommands/community/handleStar.ts`
`src/modules/commands/subcommands/games/handleMtg.ts`
Closes #851

Updated CDN links

---

src/index.ts

Updates beccas's status
Closes #844

updated becca's status

---

src/listeners/levelListener.ts

Change the xp cooldown to 5 minutes from 1 minute.
Closes #827
~~- [ ] My contribution does NOT require a documentation update.~~
The original issue specifies this requires a doc update as well. If I understand correctly, this means to open an Issue in the docs repo. Should I also submit a PR to update it? If so, where in the docs is this cooldown mentioned?

Bump XP cooldown

---

src/index.ts

Added command registration in development mode
Closes #853 

fix: [BUG] - Commands not loaded in dev #853

---

src/events/messageEvents/messageDelete.ts
src/events/messageEvents/messageUpdate.ts

This PR modifies the files messageUpdate.ts and messageDelete.ts
Closes #828

[CHORE] Updated Message Logs

---

src/events/memberEvents/memberRemove.ts
src/modules/guild/memberRemoveCleanup.ts

feat: memberRemoveCleanup

---

sample.env

Marked `OWNER_ID` as `Required` in sample.env
Closes #870 

Changed OWNER_ID to Required in sample.env

---

package-lock.json
package.json
src/config/commands/updatesData.ts

release: 16.21.0

---

src/events/messageEvents/messageUpdate.ts

- Adds the automod, sass, and triggers listeners to the message edit event.
Closes #XXXXX

feat: listeners on message edit

---

src/config/commands/artList.ts

Add the new art!
Closes #XXXXX

chore: new art

---

src/modules/commands/misc/getOrbitData.ts
src/modules/commands/subcommands/misc/handleOrbit.ts

- Adds buttons for our community to the orbit embed
- Limits leaderboard to 20 instead of 25 (to allow the extra fields)
- Cleans up the console logs.
Closes #XXXXX

feat: orbit buttons

---

package-lock.json
package.json
src/config/commands/updatesData.ts

release: v17.2.0

---

src/utils/format-text.ts
src/utils/formatText.ts
test/formatText.spec.ts

- Add format-text utility function
Closes #883
---
I wanted to get this out as a draft to get feedback, and to also get some help. As I have some tests, I'm unsure how to go about setting them up. I also wanted to possibly refactor the code to be more readable, but I don't want to do it without the tests to prevent any breakage.

Add format-text file

---

package-lock.json
package.json
src/config/commands/updatesData.ts

release: v17.3.0

---

src/database/models/LevelModel.ts
src/interfaces/database/Level.ts
src/listeners/levelListener.ts
src/modules/commands/subcommands/community/handleLeaderboard.ts
src/modules/commands/subcommands/community/handleLevel.ts
src/modules/commands/subcommands/nhcarrigan/handlePurge.ts
src/modules/guild/memberRemoveCleanup.ts

This PR updates the level logic to use individual documents per user, instead of a document for
each server. This should resolve the data collisions we've been experiencing.
Closes #XXXXX

feat: level overhaul

---

package-lock.json
package.json
src/config/commands/updatesData.ts

release: v17.4.0

---

src/listeners/levelListener.ts
src/modules/commands/subcommands/community/handleLevel.ts
src/modules/commands/subcommands/manage/handleResetLevels.ts

Fixes the bad query. Also updates the resetlevel command.
Closes #XXXXX

fix: broken levels query

---

src/database/models/_oldLevel.ts
src/server/serve.ts

Fixes the query in the leaderboard endpoint.
Closes #XXXXX

fix: leaderboard endpoint

---

package-lock.json
package.json
src/config/commands/updatesData.ts

release: v17.4.1

---

src/modules/commands/subcommands/currency/handleWeekly.ts

When the user isn't in the support server, the fetch call throws an error.
Need to catch that error separately and eat it.
Closes #XXXXX

fix: user fetch error

---

package-lock.json
package.json
src/config/commands/updatesData.ts

release: v17.4.2

---

src/config/listeners/linkRegex.ts

fix: block fb links (#985)

---

package-lock.json
package.json
src/config/commands/updatesData.ts

release: v17.4.3

---

src/modules/commands/subcommands/becca/handleAbout.ts
src/modules/commands/subcommands/becca/handleArt.ts
src/modules/commands/subcommands/becca/handleEmote.ts
src/modules/commands/subcommands/becca/handleHelp.ts
src/modules/commands/subcommands/becca/handleInvite.ts
src/modules/commands/subcommands/becca/handleProfile.ts
src/modules/commands/subcommands/becca/handleUpdates.ts
src/modules/commands/subcommands/community/handleLeaderboard.ts
src/modules/commands/subcommands/community/handleLevel.ts
src/modules/commands/subcommands/currency/handleClaim.ts

This pull request adds link buttons to many of the embed responses. This should help facilitate mobile interaction, instead of relying on links within the embed.
Closes #XXXXX

feat: more buttons

---

src/modules/commands/subcommands/becca/handleStats.ts

Adds buttons to the server vote leaderboard.
Closes #958 

feat: add server vote button

---

package-lock.json
package.json
src/config/commands/updatesData.ts

release: v17.5.0

---

src/config/listeners/linkRegex.ts

Block `co` domains
Closes #XXXXX I didn't create one 😱

fix: block co domain

---

package-lock.json
package.json
src/config/commands/updatesData.ts

release: v17.6.0

---

src/listeners/emoteListener.ts

fix: account for random nbsp

---

package-lock.json
package.json
src/config/commands/updatesData.ts

release: v17.6.1

---

src/config/listeners/linkRegex.ts

Blocks bitly links
Closes #XXXXX

fix: block bitly links

---

test/config.spec.ts

[BUG] - Issues with Config Validation testing suite 
Closes #1017

Fixed :  [BUG] - Issues with Config Validation testing suite

---

src/modules/commands/subcommands/becca/handlePing.ts

Adds database and websocket latency to the ping command.
Closes #XXXXX

feat: add latency metrics

---

package-lock.json
package.json
src/preciseMemory.d.ts
src/server/serve.ts

Adds a rate limit to the API to avoid heavy load.
Closes #XXXXX

feat: rate limiting

---

package-lock.json
package.json
src/config/commands/updatesData.ts

release: v17.7.0

---

src/config/commands/settingsChoices.ts
src/config/database/defaultServer.ts
src/database/models/ServerConfigModel.ts
src/interfaces/database/ServerConfig.ts
src/interfaces/settings/Settings.ts
src/modules/commands/config/viewSettings.ts
src/modules/commands/subcommands/moderation/handleMute.ts
src/modules/commands/subcommands/moderation/handleUnmute.ts
src/modules/settings/renderSetting.ts
src/modules/settings/setSetting.ts
src/modules/settings/validateSetting.ts

deprecation: disable mute command

---

package-lock.json
package.json
src/config/commands/userInfo.ts
src/modules/commands/server/validateChannelPerms.ts
src/modules/commands/server/validateServerPerms.ts
src/modules/commands/subcommands/community/handleSchedule.ts

feat: upgrade to discordjs 13.4.0

---

src/commands/mod.ts
src/modules/commands/subcommands/moderation/handleMute.ts
src/modules/commands/subcommands/moderation/handleUnmute.ts
src/utils/calculateMilliseconds.ts

How exciting! New timeout features!
Closes #XXXXX

feat: new timeout functionality

---

src/modules/commands/subcommands/moderation/handleBan.ts
src/modules/commands/subcommands/moderation/handleKick.ts
src/modules/commands/subcommands/moderation/handleMute.ts
src/modules/commands/subcommands/moderation/handleUnmute.ts
src/modules/commands/subcommands/moderation/handleWarn.ts
src/utils/sendModerationDm.ts

Send users a notice when they have been the target of a moderation.
Closes #XXXXX

feat: send moderation DMs

---

src/contexts/activity.ts
src/contexts/bookmark.ts
src/contexts/report.ts
src/events/memberEvents/memberAdd.ts
src/events/memberEvents/memberRemove.ts
src/events/memberEvents/memberUpdate.ts
src/events/messageEvents/messageDelete.ts
src/events/messageEvents/messageUpdate.ts
src/listeners/automod/automodLinks.ts
src/listeners/automod/automodProfanity.ts
src/listeners/heartsListener.ts
src/listeners/levelListener.ts
src/modules/commands/subcommands/becca/handleStats.ts
src/modules/commands/subcommands/community/handleSuggest.ts
src/modules/commands/subcommands/community/handleTopic.ts
src/modules/commands/subcommands/currency/handleView.ts
src/modules/commands/subcommands/emote/handleEmoteView.ts
src/modules/commands/subcommands/misc/handleUsername.ts
src/modules/commands/subcommands/moderation/handleBan.ts
src/modules/commands/subcommands/moderation/handleKick.ts
src/modules/commands/subcommands/moderation/handleMute.ts
src/modules/commands/subcommands/moderation/handleUnmute.ts
src/modules/commands/subcommands/moderation/handleWarn.ts
src/modules/commands/subcommands/triggers/handleTriggerAdd.ts
src/modules/commands/subcommands/triggers/handleTriggerRemove.ts

- `embed.setAuthor()` expects a single object instead of multiple strings
- `message.deleted` is being removed.
Closes #XXXXX

chore: deprecation cleanups

---

src/modules/commands/server/validateChannelPerms.ts
src/modules/commands/server/validateServerPerms.ts

Updates the permission validation command to include the latest set of required permissions.
Closes #XXXXX

feat: update permissions validation

---

src/commands/becca.ts
src/config/commands/adventureList.ts
src/interfaces/commands/bot/Adventure.ts
src/modules/commands/subcommands/becca/handleAdventure.ts
src/modules/commands/subcommands/becca/handleArt.ts

Adds a new `/becca adventures` command to return an image from one of Becca's adventures!
Closes #XXXXX

feat: add adventure command

---

src/modules/commands/subcommands/becca/handleStats.ts
src/modules/commands/subcommands/community/handleLeaderboard.ts
src/modules/commands/subcommands/community/handleStarCount.ts

Migrates a few of the commands that render a list of data into the new table generator.
Closes #XXXXX

feat: tables

---

src/commands/nhcarrigan.ts
src/events/guildEvents/guildDelete.ts
src/modules/commands/subcommands/nhcarrigan/handlePurge.ts

Audits the automatic data cleanups and purge options.
Closes #XXXXX

feat: audit data cleanups

---

src/commands/emote.ts
src/config/optout/EmoteOptOut.ts
src/modules/commands/subcommands/emote/handleEmoteUse.ts

Adds the configuration to allow users to opt out of the emote system.
Closes #XXXXX

feat: add emote optout

---

src/commands/becca.ts
src/modules/commands/subcommands/becca/handleHelp.ts
src/modules/commands/subcommands/becca/handlePrivacy.ts

feat: privacy command

---

package-lock.json
package.json
src/config/commands/updatesData.ts

release: v17.8.0

---

src/config/listeners/linkRegex.ts

Block links that use `ai`
Closes #1057 

fix: block "ai" links

---

src/config/listeners/linkRegex.ts

Remove `ac` links
Closes #1062 

fix: link listener config (#1062)

---

src/contexts/bookmark.ts

Removed unused import 
Closes [#1070](https://github.com/BeccaLyria/discord-bot/issues/1070)

Update Bookmark Context Command

---

src/listeners/automod/automodLinks.ts

This is a bit of an overhaul to the link detection system.
Modification of the regex will allow for better matching, removing the false positive issues when multiple links were sent. Additionally, multi-line code blocks are stripped from the content before matching, so code should no longer erroneously trigger the system.
Closes #1076 

feat: link detection overhaul

---

package-lock.json
package.json
src/events/messageEvents/messageUpdate.ts

Uses a library to detect the modified sentences in a message and render it as a diff codeblock for message edits.
Closes #XXXXX

feat: diff generator for edits

---

src/modules/commands/subcommands/becca/handleStats.ts

Now that Becca is on topGG, this enables the leaderboard in the `/becca stats` command.
Closes #XXXXX

feat: enable bot votes leaderboard

---

src/modules/server/sendVoteReminder.ts

Adds the proper link for the bot vote reminders.
Closes #XXXXX

fix: bot vote reminder text

---

src/listeners/automod/automodLinks.ts

List the matched links in the DM sent when a user's message is automodded.
Closes #XXXXX

feat: include link matches in DM

---

package-lock.json
package.json
src/config/commands/updatesData.ts

release: v17.9.0

---

src/modules/commands/subcommands/misc/handleOrbit.ts

Updates the twitter link in the about command.
Closes #XXXXX

feat: update twitter link

---

src/commands/becca.ts
src/modules/commands/subcommands/becca/handleContact.ts

Adds a `/becca contact` command to get links to contact the development team.
Closes #XXXXX

feat: add contact command

---

src/utils/registerCommands.ts

Adds a step to sort the subcommand data before sending to Discord.
Closes #XXXXX

feat: sort subcommands

---

src/commands/mod.ts
src/modules/commands/subcommands/moderation/handleBan.ts

Makes the `days` option in the `ban` call a parameter, so moderators can choose how far back to clean up (if any).
Closes #XXXXX

feat: prune in ban command

---

src/commands/reactionRole.ts

Add a beta notice to the reaction role commands.
Closes #XXXXX

chore: add beta notice to reactionroles

---

src/events/reactionEvents.ts/reactionAdd.ts
src/events/reactionEvents.ts/reactionRemove.ts
src/modules/commands/subcommands/reactionrole/handleReactionAdd.ts
src/modules/commands/subcommands/reactionrole/handleReactionList.ts

If the emoji has an ID, then it's not a default emoji and needs to be parsed.
Closes #XXXXX

fix: try proper emoji format?

---

src/utils/sendModerationDm.ts

Resolves the error for existing database entries where `appeal_link` isn't set yet.
Closes #XXXXX

fix: optional chaining

---

src/listeners/automod/automodLinks.ts

Resolves some issues with the code block detection. Should reduce false positives.
Closes #1117 

fix: better code block detection

---

.github/workflows/crowdin-upload.yml
config/crowdin.yml

Enables a crowdin upload workflow.
Closes #XXXXX

feat: add crowdin configs

---

config/crowdin.yml

Fixes the Crowdin config to actually be functional.
Closes #XXXXX

chore: fix config

---

src/commands/reactionRole.ts

feat: take reactionrole out of beta

---

src/commands/becca.ts
src/config/commands/translatorList.ts
src/config/i18n/en-GB/commands.json
src/modules/commands/subcommands/becca/handleTranslators.ts

Adds a command to list our translators... eventually.
Closes #XXXXX

feat: add translators command

---

package-lock.json
package.json
src/config/commands/updatesData.ts

release: v18.0.0

---

src/config/i18n/en-GB/commands.json
src/modules/commands/subcommands/reactionrole/handleCreate.ts

Helps to actually respond to the command.
Closes #XXXXX

fix: actually response to create

---

src/modules/commands/errorEmbedGenerator.ts
src/modules/commands/subcommands/currency/handleTwentyOne.ts

Accidentally translated the custom ID instead of the label.
Closes #XXXXX

fix: bug with 21 buttons

---

package-lock.json
package.json
src/config/commands/updatesData.ts

release: v18.1.0

---

src/config/i18n/en-GB/commands.json
src/events/interactionEvents/interactionCreate.ts
src/modules/commands/errorEmbedGenerator.ts

fix: misc issues

---

src/utils/loadCommands.ts
src/utils/loadContexts.ts

This PR replaces the path-strings used for file-handling in the source code (eg: `join(..., "src/commands")`) with \ friendly path arguments (eg: `join(..., "src", "commands")`)
Closes #1110 

chore: slash direction support for \

---

src/commands/automod.ts
src/config/commands/settingsChoices.ts
src/config/database/defaultServer.ts
src/config/i18n/en-GB/commands.json
src/config/i18n/en-GB/listeners.json
src/database/models/ServerConfigModel.ts
src/events/messageEvents/messageCreate.ts
src/interfaces/database/ServerConfig.ts
src/interfaces/listeners/ListenerHandler.ts
src/interfaces/settings/Settings.ts
src/listeners/automod/automodPhish.ts
src/modules/commands/automod/viewAutomodSettings.ts
src/modules/commands/subcommands/automod/handleAutomodAntiphish.ts
src/modules/settings/renderSetting.ts
src/modules/settings/setSetting.ts
src/modules/settings/validateSetting.ts

Enables an anti-phishing system that detects scam links and takes moderator action.
Closes #XXXXX

feat: antiphishing system

---

src/config/i18n/en-GB/commands.json
src/modules/commands/subcommands/log/handleLogSet.ts
src/modules/commands/subcommands/moderation/handleBan.ts

Fixes a few borked i18n strings that have been noted.
Closes #XXXXX

chore: fix i18n vars

---

package-lock.json
package.json
src/config/commands/updatesData.ts

release: 18.2.0

---

src/events/messageEvents/messageCreate.ts
src/modules/naomi/naomiAntiphish.ts

Owner only command for reporting new scam links to the API we use.
Closes #XXXXX

feat: add method for reporting domains

---

package-lock.json
package.json
src/events/messageEvents/messageCreate.ts
src/modules/naomi/naomiMee6.ts

Adds an owner-only module to allow for migrating existing Mee6 level data to Becca's system.
Closes #XXXXX

feat: mee6 migration

---

package-lock.json
package.json
src/config/commands/updatesData.ts

release: v18.3.0

---

src/config/i18n/en-GB/commands.json
src/modules/commands/subcommands/community/handleRole.ts
src/modules/commands/subcommands/moderation/handleHistory.ts

Fixes the currently known broken i18n strings.
Closes #XXXXX

fix: broken i18n strings

---

src/events/messageEvents/messageCreate.ts
src/events/messageEvents/messageUpdate.ts
src/listeners/automod/automodLinks.ts
src/listeners/emoteListener.ts
src/modules/events/reactionButtonClick.ts
src/modules/events/runNaomiCommands.ts
src/utils/generateDiff.ts
src/utils/sleep.ts

General maintenance + cleanup
Closes #XXXXX

chore: clean up code smells

---

package-lock.json
package.json
src/config/commands/updatesData.ts

release: v18.3.1

---

src/index.ts

chore: enable sentry releases

---

sample.env
src/interfaces/BeccaLyria.ts
src/modules/events/runNaomiCommands.ts
src/modules/naomi/naomiTopgg.ts
src/modules/validateEnv.ts

Adds an owner command to update the guild count for the bot's topgg page.
Closes #1202 

feat: topgg owner command

---

package-lock.json
package.json
src/config/commands/updatesData.ts

release: v18.4.0

---

package-lock.json
package.json
src/commands/userConfig.ts
src/config/i18n/en-GB/commands.json
src/database/models/UserConfigModel.ts
src/interfaces/commands/UserConfigCommandHandler.ts
src/interfaces/database/UserConfig.ts
src/modules/commands/community/generateLevelHtml.ts
src/modules/commands/community/generateLevelImage.ts
src/modules/commands/subcommands/community/handleLevel.ts
src/modules/commands/subcommands/userconfig/handleLevelCard.ts
src/modules/commands/subcommands/userconfig/handleUserConfigView.ts

This PR adds level images to the `/community level` command. Additionally creates a new `/userconfig` command that will control user-specific settings - currently, this will only be colours for the level card at the moment.
Closes #XXXXX

feat: level images

---

src/modules/commands/community/generateLevelHtml.ts

Tweaks the level cards a bit.
Closes #XXXXX

feat: tweak level card layout

---

src/commands/reactionRole.ts
src/config/i18n/en-GB/commands.json
src/modules/commands/subcommands/reactionrole/handleAdd.ts
src/modules/commands/subcommands/reactionrole/handleRemove.ts

Allows roles to be added/removed on a reaction role post.
Closes #XXXXX

feat: reaction role edits

---

package-lock.json
package.json
src/config/commands/updatesData.ts

release: v18.5.0

---

package-lock.json
package.json
src/config/commands/updatesData.ts

release: v18.5.1

---

src/config/i18n/en-GB/listeners.json
src/listeners/automod/automodPhish.ts

Adds the sinking yacht API, and establishes the pattern/infrastructure to support multiple anti-phishing API sources.
Closes #XXXXX

feat: add support for multiple phishing APIs

---

src/interfaces/BeccaLyria.ts
src/listeners/automod/automodPhish.ts
src/modules/naomi/naomiAntiphish.ts
src/modules/validateEnv.ts

:sparkles: feat/add-heptagram-api

---

package-lock.json
package.json
sample.env
src/config/commands/updatesData.ts

release: v18.6.0

---

src/listeners/automod/automodPhish.ts

feat: individual API error handling

---

src/listeners/automod/automodPhish.ts

fix: encode link?

---

src/listeners/automod/automodPhish.ts

feat: extract domain

---

src/modules/commands/subcommands/moderation/handleBan.ts
src/modules/commands/subcommands/moderation/handleHistory.ts

Fixes the incorrect boolean check.
Closes #XXXXX

fix: mod permission checks

---

src/listeners/automod/automodPhish.ts

Bugfix with authentication to Heptagram api

---

src/listeners/automod/automodPhish.ts

fix: proper response structure

---

package-lock.json
package.json
src/config/commands/updatesData.ts

release: v19.0.0

---

src/commands/currency.ts
src/commands/subcommands/currency/handleClaim.ts
src/commands/subcommands/currency/handleDaily.ts
src/commands/subcommands/currency/handleSlots.ts
src/commands/subcommands/currency/handleWeekly.ts
src/config/i18n/en-GB/commands.json

- Increases the rate of currency gain
- Increases the payouts for slots
- Allows for partial wins on the slots
- Changes the currency rewards
Closes #XXXXX

feat: updates to currency system

---

package-lock.json
package.json
src/config/commands/updatesData.ts

release: v19.0.1

---

src/listeners/automod/automodLinks.ts

This PR changes the link regex to look for `http` or `https` - should reduce the false positives from things like `package.json`.
Closes #XXXXX

feat: less aggressive link detection

---

package-lock.json
package.json
src/config/commands/updatesData.ts

release: v19.0.2

---

src/database/models/VoterModel.ts
src/interfaces/database/Voter.ts
src/modules/server/sendVoteMessage.ts
src/modules/server/sendVoteReward.ts
src/server/serve.ts

Adds a system to track monthly votes. Users who vote for the bot and/or server 60 times in a month can be given a special role in the server.
Closes #XXXXX

feat: add system for monthly vote rewards

---

package-lock.json
package.json
src/config/commands/updatesData.ts

release: v19.1.0

---

src/commands/subcommands/community/handleLeaderboard.ts
src/commands/subcommands/community/handleLevel.ts
src/commands/subcommands/community/handleStarCount.ts
src/server/serve.ts

Remove the web-view leaderboards for privacy purposes.
Closes #XXXXX

feat: remove starboard and leaderboard

---

package-lock.json
package.json
src/config/commands/updatesData.ts

release: v19.1.1

---

package.json
test/__mocks__/statics.ts
test/root.ts
test/utils/beccaLogHandler.spec.ts
test/utils/calculateMilliseconds.spec.ts
test/utils/customSubstring.spec.ts
test/utils/getLangCode.spec.ts
test/utils/loadCommands.spec.ts
test/utils/loadContexts.spec.ts
test/utils/parseSeconds.spec.ts
test/utils/replaceHtml.spec.ts
test/utils/scheduleCurrencyReminder.spec.ts
test/utils/sleep.spec.ts

feat: utils tests

---

src/listeners/levelListener.ts

feat: decrease experience cooldown

---

package-lock.json
package.json
src/config/commands/updatesData.ts

release: v19.1.2

---

src/config/commands/settingsChoices.ts
src/config/database/defaultServer.ts
src/database/models/ServerConfigModel.ts
src/events/memberEvents/memberAdd.ts
src/interfaces/database/ServerConfig.ts
src/interfaces/settings/Settings.ts
src/modules/commands/config/viewSettings.ts
src/modules/settings/renderSetting.ts
src/modules/settings/setSetting.ts
src/modules/settings/validateSetting.ts

Adds an option for setting an initial experience value on member join.
Closes #XXXXX

feat: add option for initial experience value

---

package-lock.json
package.json
src/config/commands/updatesData.ts

release: v19.2.0

---

src/events/memberEvents/memberAdd.ts

fix: only assign initial xp if levels are on

---

src/commands/subcommands/moderation/handleBan.ts
src/commands/subcommands/moderation/handleKick.ts

Catch the missing member error and handle properly.
Closes #XXXXX

fix: respond when member is not in guild

---

package-lock.json
package.json
src/config/commands/updatesData.ts

release: v20.0.0

---

src/commands/subcommands/currency/handleTwentyOne.ts
src/config/IntentOptions.ts

fix: message content

---

package-lock.json
package.json
src/config/commands/updatesData.ts

release: v20.0.1

---

src/config/listeners/defaultHearts.ts
src/listeners/heartsListener.ts
test/config/listeners.spec.ts

This was a fun thing to have, but now that we're operating at a larger scale, this should be something servers explicitly configure.
Closes #XXXXX

chore: remove default hearts

---

src/commands/subcommands/community/handleLeaderboard.ts

feat: paginate leaderboard

---

package-lock.json
package.json
src/config/commands/updatesData.ts

release: v20.1.0

---

src/commands/subcommands/currency/handleDaily.ts
src/commands/subcommands/currency/handleWeekly.ts

This PR adjusts the earnedCurrency so that the daily/weekly rewards shouldn't be 0. 
Closes #1188 

feat: changed currency rounding

---

.editorconfig

This is an essential feature for developers everywhere.
All it does is literally add an .editorconfig file based on the standard line breaks preferred by the code-base. 
Closes #XXXXX

Create an .editorconfig

---

src/listeners/automod/automodPhish.ts
src/modules/naomi/naomiAntiphish.ts

Fixes up some slight errors I noticed with the Heptagram API code.
Closes #XXXXX

:bug: Fixing up some heptagram api related stuff

---

sample.env
src/commands/becca.ts
src/commands/subcommands/becca/handleFeedback.ts
src/commands/subcommands/becca/handleFeedbackModal.ts
src/config/i18n/en-GB/commands.json
src/events/interactionEvents/interactionCreate.ts
src/index.ts
src/interfaces/BeccaLyria.ts
src/modules/validateEnv.ts

Adds a feedback command so users can submit feedback directly through Discord.
Closes #XXXXX

feat: add feedback command

---

package-lock.json
package.json
src/config/commands/updatesData.ts

release: v20.2.0

---

src/config/i18n/en-GB/commands.json

fix: include link to server in feedback response

---

src/commands/manage.ts
src/commands/subcommands/manage/handleSuggestion.ts

fix: add suggestion fields manually in edit call

---

package-lock.json
package.json
src/config/commands/updatesData.ts
test/config/commands.spec.ts

release: v20.2.1

---

package-lock.json
package.json

This PR makes the prebuild script cross-platform by using `rimraf` instead of `rm`.
Closes #1364

feat: make prebuild script work on all platforms

---

package-lock.json
package.json

chore(deps): update discord.js to 14.6.0

---

.github/workflows/codeql-analysis.yml
.github/workflows/node-ci.yml
package.json

chore: node 18

---

src/commands/subcommands/config/handleSet.ts
src/commands/welcome.ts
src/config/database/defaultServer.ts
src/database/models/ServerConfigModel.ts
src/events/memberEvents/memberAdd.ts
src/events/memberEvents/memberUpdate.ts
src/interfaces/database/ServerConfig.ts
src/interfaces/settings/Settings.ts
src/modules/naomi/naomiMee6.ts
src/modules/settings/renderSetting.ts
src/modules/settings/setSetting.ts

Allows servers to toggle between embedded welcome messages or raw text welcome messages.
Closes #1378 

feat: toggle welcome message style

---

.gitignore
src/commands/community.ts
src/commands/config.ts
src/commands/subcommands/community/handleTicket.ts
src/config/database/defaultServer.ts
src/config/i18n/en-GB/commands.json
src/database/models/ServerConfigModel.ts
src/events/interactionEvents/interactionCreate.ts
src/events/messageEvents/messageCreate.ts
src/interfaces/database/ServerConfig.ts
src/interfaces/settings/Settings.ts
src/modules/settings/renderSetting.ts
src/modules/settings/setSetting.ts
src/modules/tickets/createLogFile.ts
src/modules/tickets/generateTicketLog.ts
src/modules/tickets/logTicketMessage.ts

Adds a ticketing system.
Closes #1370 

feat: ticket system

---

src/commands/config.ts
src/config/database/defaultServer.ts
src/database/models/ServerConfigModel.ts
src/events/handleEvents.ts
src/events/reactionEvents/reactionAdd.ts
src/index.ts
src/interfaces/database/ServerConfig.ts
src/interfaces/settings/Settings.ts
src/modules/settings/renderSetting.ts
src/modules/settings/setSetting.ts

Adds a basic starboard system.
Closes #1366

feat: starboard system

---

src/commands/community.ts
src/commands/subcommands/community/handlePoll.ts
src/database/models/PollModel.ts
src/events/interactionEvents/interactionCreate.ts
src/index.ts
src/interfaces/database/Poll.ts

Updates the poll system to no longer be cache reliant, and to persist in the database as needed.
Closes #1376 

feat: make polls persistent

---

src/commands/levels.ts
src/config/database/defaultServer.ts
src/database/models/ServerConfigModel.ts
src/interfaces/database/ServerConfig.ts
src/interfaces/settings/Settings.ts
src/listeners/levelListener.ts
src/modules/settings/renderSetting.ts
src/modules/settings/setSetting.ts

Implements a level decaying system.
Closes #1305

feat: level decay

---

src/commands/automod.ts
src/commands/community.ts
src/commands/config.ts
src/commands/levels.ts
src/commands/log.ts
src/commands/reactionRole.ts
src/commands/welcome.ts

chore: add channel type validation to all commands

---

package-lock.json
package.json
src/config/commands/updatesData.ts
src/config/i18n/en-GB/commands.json

release: v21.0.0

---

src/events/messageEvents/messageCreate.ts

fix: only process ticket messages in set category

---

src/commands/subcommands/reactionrole/handleCreate.ts

feat: automatic role icon support

---

src/config/i18n/en-GB/defaults.json

chore: no custom link

---

src/commands/mod.ts
src/commands/subcommands/moderation/handleBan.ts
src/commands/subcommands/moderation/handleHistory.ts
src/commands/subcommands/moderation/handleKick.ts
src/commands/subcommands/moderation/handleMute.ts
src/commands/subcommands/moderation/handleUnban.ts
src/commands/subcommands/moderation/handleUnmute.ts
src/config/i18n/en-GB/commands.json
src/database/models/HistoryModel.ts
src/interfaces/commands/moderation/ModerationActions.ts
src/interfaces/database/History.ts
src/modules/commands/moderation/updateHistory.ts

feat: add unban command

---

src/config/i18n/en-GB/events.json
src/events/handleEvents.ts
src/events/memberEvents/memberUpdate.ts
src/events/userEvents/userUpdate.ts

feat: improved member update logging

---

package-lock.json
package.json
src/commands/subcommands/becca/handleUpdates.ts
src/config/commands/updatesData.ts
src/config/i18n/en-GB/commands.json

release: v21.1.0

---

src/config/i18n/en-GB/events.json
src/database/models/MessageCountModel.ts
src/events/memberEvents/memberRemove.ts
src/events/messageEvents/messageCreate.ts
src/interfaces/database/MessageCount.ts
src/listeners/messageCountListener.ts
src/modules/guild/memberRemoveCleanup.ts
test/database/schema.spec.ts

feat: message counts

---

package.json

chore(tools): lint test directory

---

src/commands/subcommands/config/handleSet.ts
src/config/commands/settingsPermissions.ts
src/config/i18n/en-GB/commands.json

feat: validate settings that require permissions

---

package-lock.json
package.json
src/config/IntentOptions.ts
src/events/guildEvents/guildAuditLogEntryCreate.ts
src/events/handleEvents.ts
src/modules/events/getModActionFromAuditLog.ts

feat: audit log

---

src/events/automodEvents/autoModerationActionExecution.ts
src/events/handleEvents.ts

feat: capture automod mutes

---

package-lock.json
package.json
src/config/commands/updatesData.ts

release: v21.2.0

---

src/events/guildEvents/guildAuditLogEntryCreate.ts

feat: log reason and moderator

---

package-lock.json
package.json
src/commands/subcommands/games/handleHabitica.ts
src/modules/naomi/naomiUnregisterCommand.ts
src/modules/naomi/naomiViewCommands.ts
src/utils/registerCommands.ts

chore: update dependencies

---

src/commands/subcommands/config/handleSet.ts

fix: confirm is channel setting before validating channel perms

---

package-lock.json
package.json
src/config/commands/updatesData.ts

release: v21.2.1

---

src/commands/subcommands/becca/handleContact.ts
src/commands/subcommands/misc/handleOrbit.ts
src/config/i18n/en-GB/commands.json

chore: replace twitter links with mastodon

---

src/modules/validateEnv.ts

It makes the two keys, Habitica and Orbit , actually optional; thus passing validation if they were missing. 
Closes #1615

Fix: Make the orbit and habitica keys optional

---

sample.env

It updates the sample.env and replaces localhost with 127.0.0.1in the url
Closes #1621

Fix - Allow users to more easily connect out of the box with MongoDB

---

src/commands/subcommands/community/handlePoll.ts
src/commands/subcommands/currency/handleTwentyOne.ts
src/commands/subcommands/currency/handleView.ts

It fixes the typo I made in the last PR and updates the other manual timestamp usage to use a function instead.
Closes #XXXXX

Chore: cleanup the timestamp usage and fix time usage.

---

src/config/i18n/en-GB/commands.json

chore: change i18n verbiage to work with timestamps

---

src/events/messageEvents/messageCreate.ts

Because I talk in third person too much.
Closes #XXXXX

chore: add prefix to owner commands

---

package-lock.json
package.json
src/config/commands/updatesData.ts

release: v21.3.0

---

src/commands/subcommands/becca/handleAdventure.ts
src/commands/subcommands/becca/handleArt.ts
src/commands/subcommands/becca/handleEmote.ts

My PR contains the CDN link for 3 commands - emote, adventure, art. As mentioned in the issue, I have updated them via this PR.
Closes #1645 

Migrate image links to CDN

---

package-lock.json
package.json
prisma/schema.prisma
src/database/connectPrisma.ts
src/index.ts
src/interfaces/BeccaLyria.ts

This PR starts prepping the database migration
- Schema is written
- Connection logic is written
Closes #XXXXX

feat: prepare for prisma migration

---

prisma/schema.prisma
src/commands/subcommands/triggers/handleTriggerAdd.ts
src/commands/subcommands/triggers/handleTriggerRemove.ts
src/commands/subcommands/triggers/handleTriggerView.ts
src/config/database/defaultServer.ts
src/database/models/ServerConfigModel.ts
src/interfaces/database/ServerConfig.ts
src/interfaces/settings/Trigger.ts
src/listeners/triggerListener.ts
src/modules/events/runNaomiCommands.ts
src/modules/naomi/naomiMigrate.ts

This will allow for proper Prisma typing.
Closes #XXXXX

chore: migrate triggers from an array to an object

---

package-lock.json
package.json
src/config/commands/updatesData.ts

release: v21.4.0

---

src/events/interactionEvents/interactionCreate.ts

Also use modal submit method why not
Closes #XXXXX

chore: update deprecated method

---

prisma/schema.prisma

chore: remove old triggers from schema

---

src/commands/subcommands/moderation/handleWarn.ts

fix: include user id in warning embed

---

package-lock.json
package.json
src/config/commands/updatesData.ts

release: v22.0.0

---

src/modules/guild/memberRemoveCleanup.ts

This (theoretically) only errors if the record doesn't exist.
We don't care if it doesn't exist - we wanted to delete it anyway.
Closes #XXXXX

chore: suppress delete errors

---

sample.env
src/commands/becca.ts
src/commands/subcommands/becca/handleAnnouncements.ts
src/config/i18n/en-GB/commands.json
src/interfaces/BeccaLyria.ts
src/modules/validateEnv.ts

Adds a command that automatically follows the announcement channel from our support server.
Closes #XXXXX

feat: announcements command

---

src/commands/subcommands/currency/handleWeekly.ts

chore: add missing await

---

src/modules/settings/setSetting.ts
src/modules/settings/settingsSetters.ts

fix: actually save setting changes to db

---

src/config/i18n/en-GB/events.json
src/modules/events/interactions/buttons/buttonIsReaction.ts

feat: add response when failing to manage roles

---

src/events/guildEvents/guildDelete.ts

Prisma throws an error when there's nothing to delete, which seems silly and we aren't concerned about that.
Closes #XXXXX

chore: suppress prisma errors on guild delete

---

src/modules/listeners/processLevelRoles.ts

chore: notify when cannot assign level role

---

package-lock.json
package.json
src/config/commands/updatesData.ts

release: v22.1.0

---

src/commands/subcommands/moderation/handleBan.ts
src/commands/subcommands/moderation/handleKick.ts
src/commands/subcommands/moderation/handleMute.ts
src/commands/subcommands/moderation/handleUnban.ts
src/commands/subcommands/moderation/handleUnmute.ts
src/commands/subcommands/moderation/handleWarn.ts
src/listeners/heartsListener.ts
src/listeners/levelListener.ts
src/utils/FetchWrapper.ts
src/utils/debugLogger.ts

chore: further improvements to error handling

---

src/utils/registerCommands.ts

feat: respond to command registration call

---

.github/workflows/deploy-coverage.yml

fix(tools): coverage ci

---

src/commands/subcommands/support/handleIds.ts
src/commands/support.ts
src/config/i18n/en-GB/commands.json

It adds a sub command to support so inexperienced bot users can 
Closes #1744

Chore: Create an ids subcommand

---

src/index.ts

feat: add custom status

---

src/commands/subcommands/community/handleLeaderboard.ts

fix: correct the new leaderboard logic

---

.github/workflows/deploy-coverage.yml
.npmrc
.nycrc.json
package.json
pnpm-lock.yaml
test/validateCoverage.ts

chore(tools): clean up test commands

---

src/commands/currency.ts
src/config/i18n/en-GB/commands.json
src/config/i18n/en-GB/defaults.json

chore: update chat link

---

src/commands/misc.ts
src/commands/subcommands/misc/handleEcho.ts

It creates an command that allows members to send a message from Becca's account. 
Closes #1895
Note: It's not been thoroughly tested because I was having some unexpected difficulties with Prisma. Additionally it appears that setting the permission for the command is impossible without adjusting the permissions for *all* the sub commands.

Feature: Create an echo command.

---

.github/workflows/codeql-analysis.yml
.github/workflows/deploy-coverage.yml
.github/workflows/node-ci.yml
package.json

chore: move to node 20

---

src/commands/misc.ts
src/commands/subcommands/misc/handleEcho.ts

fix: move ephemeral logic

---

src/listeners/emoteListener.ts

fix: allow 19 digit emote ids

---

package.json
src/config/commands/updatesData.ts

release: v22.5.1

---

src/config/CallToAction.ts
src/events/interactionEvents/interactionCreate.ts
src/interfaces/BeccaLyria.ts
src/modules/ctaWrapper.ts
src/modules/events/interactions/processButtonClick.ts
src/modules/prepareBecca.ts

feat: add donation cta

---

src/contexts/activity.ts

feat: convert activity context to ephemeral

---

src/commands/subcommands/support/handleDataRequest.ts
src/commands/support.ts

*You may ~~fire~~ merge when ready.*
Implements the `/support data-request` command, which allows users to request data that Becca has stored that pertains to them.
Closes #1743

feat: `/support data-request` command

---

src/config/CallToAction.ts

feat: enter maintenance mode

---

src/events/clientEvents/disconnect.ts
src/events/clientEvents/ready.ts
src/events/guildEvents/guildCreate.ts
src/events/guildEvents/guildDelete.ts
src/events/shardEvents/shardReady.ts
src/listeners/automod/automodPhish.ts
src/modules/naomi/naomiUnregisterCommand.ts
src/utils/beccaErrorHandler.ts

feat: include avatar and username in webhook
