src/commands/github.ts

This PR adjusts the handling for the github command when there are no public repositories for the queried user. Rather than returning nothing, the command now returns an embed sans repository links.
Closes #XXXXX

Better handling for no public repos

---

src/main.ts

Instead of mentioning a user when they are added to the guild, it uses inline code markdown to display their username.
Closes #176

Fix #176 - Leaving guild changes mention

---

src/commands/bot/privacy.ts
test/unit/commands/bot/privacy.spec.ts

Adds tests for the `privacy` functionality.
Note: The tests do not use the `PRIVACY_CONSTANT` on purpose so it is clear when values change the tests will fail.
Chips away at #199 

test(command): add tests for privacy command

---

src/commands/bot/report.ts
test/unit/commands/bot/report.spec.ts

Adds tests for the `report` functionality.
Note: The tests do not use the `REPORT_CONSTANTS` on purpose so it is clear when values change the tests will fail.
Chips away at #199 

test(command): add tests for report command

---

src/commands/bot/art.ts
test/unit/commands/bot/art.spec.ts

Adds test coverage over `art` command
Note: The tests do not use the `ART_CONSTANTS` on purpose so it is clear when values change the tests will fail.
Chips away at #199

test(command): add coverage over art

---

package.json
src/commands/server/role.ts

Modifies the `role` command to accept `listall` instead of a role. This returns a list of self-assignable roles for that server.
Closes #XXXXX
For _any_ version updates, please verify if the [documentation page](https://www.nhcarrigan.com/Becca-Lyria-documentation) needs an update. If it does, please [create an issue there](https://github.com/nhcarrigan/Becca-Lyria-documentation/issues/new?assignees=nhcarrigan&labels=%F0%9F%9A%A6+status%3A+awaiting+triage&template=update.md&title=%5BUPDATE%5D) to ensure it is not forgotten.

Add role list function

---

package-lock.json
package.json
src/botConnect.ts

Removes the dynamic loading of the `dotenv` package. With Becca moving
to DigitalOcean, the `dotenv` package is always needed.
Closes #XXXXX

feat: remove dynamic import

---

CONTRIBUTING.md
package-lock.json
package.json
src/commands/bot/about.ts

Signed-off-by: galahad42 <amritanand1407@gmail.com>
Removes `users` field from the embed in `about` command
Closes #519 

fix: remove users field from about command

---

package-lock.json
package.json
src/listeners/levelsListener.ts

This PR will remove the "UP!" (:up:) reaction of the bot to the messages which have fetched the experience points to the user.
Closes #666

fix: Removed the UP! reaction for messages

---

package-lock.json
package.json
src/commands/server/level.ts

Updates the `level` command to take an optional `user` parameter to see someone else's levels.
Closes #688 

feat: see user's levels

---

package-lock.json
package.json
src/config/database/defaultServer.ts
src/listeners/linksListener.ts

Converts anti-link message to an embed, updates `link_message` to allow `{@username}` for ping replacement.
Closes #724 
(for real this time!)

feat: link message ping

---

package.json
src/listeners/linksListener.ts

File extension like `.txt` are not allowed, as they are detected as links.
closes #752 
Did you remember to update the `package.json` version number? 
Usage example...

fix: regex allow file extensions (#752)

---

.gitignore
src/modules/commands/subcommands/becca/handleUpdates.ts

A new field is added so that whenever we run` \becca updates` we see the current version.
Closes #835 

Feat: version field added

---

.github/PULL_REQUEST_TEMPLATE.md

Changed the link of contributing guidelines from CONTRIBUTING.md to the [contribute.md](https://docs.beccalyria.com/#/contribute.md) from the docs in the `PULL_REQUEST_TEMPLATE.md`
Closes #869 

Changed the link of contributing guidlines in the PR Template

---

src/config/commands/settingsChoices.ts
src/config/database/defaultServer.ts
src/database/models/ServerConfigModel.ts
src/events/messageEvents/messageCreate.ts
src/interfaces/database/ServerConfig.ts
src/interfaces/settings/ArraySettings.ts
src/interfaces/settings/Settings.ts
src/listeners/emoteListener.ts
src/modules/commands/config/viewSettings.ts
src/modules/settings/renderSetting.ts
src/modules/settings/setSetting.ts
src/modules/settings/validateSetting.ts

This PR adds a new config allowing servers to set a channel to be emote only. Messages containing anything other than emotes will be deleted from those channels.
Closes #XXXXX

feat: emote-only channels

---

src/modules/commands/subcommands/manage/handleXpModify.ts

- Allows the moderator to assign enough XP that increases/decreases the user's level, and adjusts the level accordingly.
- Adds/removes level roles in response to the user's new level.
- Cleans up the optional chaining.
Closes #XXXXX

fix: xpmodify logic

---

src/server/serve.ts

Restricts the API endpoint for server leaderboards to the first 100 documents. This will limit the DDoS attack vector and ensure the database doesn't get locked up when viewing large servers.
Closes #XXXXX

fix: limit leaderboard API to 100

---

src/modules/commands/subcommands/games/handleHabitica.ts

This PR fixes the Achievements embed shown for `/games habitica` command, even when there as no user found.
| Before | After |
| :-: | :-: |
| ![Image from before. Both user not found and no achievements embed](https://user-images.githubusercontent.com/91655303/139568443-f5470c18-7c15-4137-bef0-7e5ccc64b013.png) | ![image after PR. There is no embed for achievements if there is no user found](https://user-images.githubusercontent.com/62864373/146737221-10676f6f-a9eb-4b89-b19b-7f1231d6999f.png) |
Closes #957 
For _any_ version updates, please verify if the [documentation page](https://www.beccalyria.com/discord-documentation) needs an update. If it does, please [create an issue there](https://github.com/BeccaLyria/discord-documentation/issues/new?assignees=nhcarrigan&labels=%F0%9F%9A%A6+sta …

fix: no achivements when no habitica user found

---

src/modules/commands/subcommands/becca/handleAdventure.ts

As mentioned, the URL in .setUrl of handleAdventure.ts has been changed.
Closes #1097
My contribution does NOT require a documentation update.

fix: update link in adventure command

---

src/config/commands/settingsChoices.ts
src/config/database/defaultServer.ts
src/database/models/ServerConfigModel.ts
src/interfaces/database/ServerConfig.ts
src/interfaces/settings/Settings.ts
src/modules/commands/config/viewSettings.ts
src/modules/commands/subcommands/moderation/handleBan.ts
src/modules/commands/subcommands/moderation/handleKick.ts
src/modules/commands/subcommands/moderation/handleMute.ts
src/modules/commands/subcommands/moderation/handleUnmute.ts
src/modules/commands/subcommands/moderation/handleWarn.ts
src/modules/settings/renderSetting.ts
src/modules/settings/setSetting.ts
src/modules/settings/validateSetting.ts
src/utils/sendModerationDm.ts

This PR adds a config setting for ban appeal link, where a server can provide a link to a Google Form (or other option) for appealing a ban. Then, when a user is banned, if this config is set, Becca includes the value in the DM sent to the user.
- Appeal link in the DM sent on ban
- Setting the config link
- Config View Embed
Closes #1071

feat: ban appeal link config

---

src/listeners/automod/automodLinks.ts

Modifies the automodLinks Listener, and adds a 5 minute timeout to the "Invalid-link" prompt.
Closes #1088 

feat: timeout invalid-link prompt

---

src/commands/reactionRole.ts
src/database/models/ReactionRoleModel.ts
src/events/clientEvents/ready.ts
src/events/handleEvents.ts
src/events/reactionEvents.ts/reactionAdd.ts
src/events/reactionEvents.ts/reactionRemove.ts
src/interfaces/database/ReactionRole.ts
src/modules/commands/subcommands/reactionrole/handleReactionAdd.ts
src/modules/commands/subcommands/reactionrole/handleReactionList.ts
src/modules/commands/subcommands/reactionrole/handleReactionRemove.ts
src/utils/cacheReactionRoles.ts
test/schema.spec.ts

By popular demand...
- Adds reaction role commands to manage the system
- Adds database schema to store reaction roles
- Adds step to cache messages on boot
- Adds listeners to the reaction events to assign/remove roles accordingly
Closes #XXXXX

feat: add reaction role system

---

src/utils/cacheReactionRoles.ts

Use a `Set` to ensure we don't fetch the same message more than once (for multiple reaction roles on a single message).
Closes #XXXXX

fix: don't fetch messages more than once

---

src/events/memberEvents/memberRemove.ts

This PR changes the member leave flow. If a member is `pending` (has not completed the server verification), rather than sending the leave message in the departure channel, send it in the member events log channel.
Closes #1197 

feat: send log embed if member is pending when removed

---

src/listeners/beccaMentionListener.ts
src/listeners/heartsListener.ts
src/modules/commands/subcommands/community/handleSuggest.ts

Adds `.catch` statements to the few reaction calls Becca makes, attempting another reaction with a fallback default emote.
The purpose of this is to use custom emotes through the `.env` settings again, while suppressing error logs for servers that did not grant the use external emote permission.
Closes #XXXXX

feat: add emote fallbacks

---

src/config/commands/settingsChoices.ts
src/config/database/defaultServer.ts
src/config/i18n/en-GB/commands.json
src/database/models/ServerConfigModel.ts
src/interfaces/database/ServerConfig.ts
src/interfaces/settings/ArraySettings.ts
src/interfaces/settings/Settings.ts
src/modules/commands/config/viewSettings.ts
src/modules/commands/subcommands/community/handleRole.ts
src/modules/settings/renderSetting.ts
src/modules/settings/setSetting.ts
src/modules/settings/validateSetting.ts

Deprecates the `/community role` command in favour of the reaction role system, to reduce load on the database.
Closes #XXXXX

feat: deprecate self-assignable roles

---

src/listeners/automod/automodPhish.ts

Use the correct URL.
Closes #XXXXX

fix: correct heptagram api url

---

src/config/commands/settingsChoices.ts
src/config/database/defaultServer.ts
src/config/i18n/en-GB/commands.json
src/database/models/ServerConfigModel.ts
src/interfaces/database/ServerConfig.ts
src/interfaces/settings/Settings.ts
src/listeners/levelListener.ts
src/modules/commands/config/viewSettings.ts
src/modules/listeners/generateLevelText.ts
src/modules/listeners/generateRoleText.ts
src/modules/settings/renderSetting.ts
src/modules/settings/setSetting.ts
src/modules/settings/validateSetting.ts

This makes the level up responses configurable.
- Servers can set a custom level up message where:
- `{user}` is replaced with the user's tag
- `{@user}` is replaced with the user mention
- `{level}` is replaced with the user's level
- Servers can set a custom level role gain message where:
- `{user}` is replaced with the user's tag
- `{@user}` is replaced with the user mention
- `{role}` is replaced with the role's name
- `{@role}` is replaced with the role mention
- Servers can toggle between `embed` and `text` style messages.
Closes #XXXXX
For _any_ version updates, please verify if the [documentation page](https://docs.beccalyria.com?utm_source=github&utm_medium=pr-template) needs an update. If it does, please [create an issue …

feat: make role/level messages configurable

---

src/commands/subcommands/currency/handleView.ts

`dailyCooldown` and `weeklyCooldown` were representing the number of seconds before the user could claim the reward again. This was intended to run in the `parseSeconds` function.
Since we moved to timestamps, we don't need the number of seconds here - instead, we just check if the cooldown is earlier than Date.now().
Closes #XXXXX

fix: timestamp logic in currency view

---

src/commands/automod.ts

This PR adds the subcommand `links` and `profanity` for the `automod` command, so that the system can be toggled on and off. These were lost during the config overhaul (https://github.com/BeccaLyria/discord-bot/commit/a6515e95356e03e1dc9526e4dd67485404d6d74b#diff-ce069ee9d6e6d976c4684b24a1094617a768d4a0093dcffc74d371729ca983f3L81-L102).
Closes #XXXXX

fix: add automod links and profanity subcommands

---

src/commands/subcommands/currency/handleDaily.ts
src/commands/subcommands/currency/handleSlots.ts
src/commands/subcommands/currency/handleTwentyOne.ts
src/commands/subcommands/currency/handleWeekly.ts

It modified the handleDaily, handSlots, handleTwentyOne, and handleWeekly sub commands in the currency command to use Discord's timestamp feature.  
Closes  #1596
As an aside, I remember seeing Discord's timestamp system used manually in the codebase. I think it'd be more legible if the function was used instead, but it is outside of the scope of this PR.

Chore: Use timestamps for currency commands

---

sample.env
src/interfaces/BeccaLyria.ts
src/modules/Analytics.ts
src/modules/prepareBecca.ts
src/modules/validateEnv.ts

Achieves a few things:
- Adds a toggle that suppresses the `fetch` calls in the analytics, and uses a log instead.
- Makes the `ANALYTICS_SECRET` optional.
- Adds an `ANALYTICS_URL` env to allow for local testing of the analytics server, if desired.
Closes #XXXXX

feat: toggle analytics

---

src/commands/subcommands/currency/handleDaily.ts
src/commands/subcommands/currency/handleSlots.ts
src/commands/subcommands/currency/handleTwentyOne.ts
src/commands/subcommands/currency/handleWeekly.ts

It updates the codebase to no longer use magic numbers for remaining time in the currency commands and attempts to fix the invalid remaining usage time. 
Closes #XXXXX

Chore: Remove magic numbers and try to fix currency reminders.

---

src/commands/subcommands/support/handleServer.ts

Fixes `/support server` response. At the moment, it pulls `commands:support.server` from `i18n`, when it should be pulling `commands:support.server.response`.

fix: `/support server` command response

---

prisma/schema.prisma
src/commands/becca.ts
src/commands/subcommands/becca/handleStats.ts
src/events/guildEvents/guildDelete.ts
src/modules/naomi/naomiPurgeData.ts
src/server/serve.ts

This removes the `commands` model from prisma. This removes the `commands` view from the `/becca stats`  command and the logic behind it. The commands deletion from the `guildDelete` event handler is removed. The `commands` deletion is removed from the `naomiPurgeData`  command. And the `/stats/:stat` and `commands` endpoints have been removed. 
Closes #1742

chore: remove old command tracking model and logic

---

src/commands/community.ts

Changed the poll duration description from  ``` .setDescription("The length of time to mute the user.") ```  to  
```  .setDescription("The length of time for the poll to remain active.") ```
Closes #1888 

fix:changed the poll duration description
